package edu.fiuba.algo3.controladores;

import edu.fiuba.algo3.control.ControladorPrimario;
import edu.fiuba.algo3.control.GameLauncher;
import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.input.MouseEvent;

public class MenuPrincipalController extends ControladorPrimario{
	@FXML
	public Button botonNuevaPartida;
	@FXML
	public Button botonSalir;

	// Event Listener on Button[#botonNuevaPartida].onMouseClicked
	@FXML
	public void botonNuevaPartidaActivado(MouseEvent event) {
		GameLauncher unLanzador = new GameLauncher();
		unLanzador.iniciar(this.myStage, "/Vistas/Menu/MenuCrearJugador.fxml");
	}
	// Event Listener on Button[#botonSalir].onMouseClicked
	@FXML
	public void botonSalirActivado(MouseEvent event) {
		// TODO Autogenerated
	}
}
